2025-05-24 17:13:42,041 INFO    MainThread:11003 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-05-24 17:13:42,041 INFO    MainThread:11003 [wandb_setup.py:_flush():70] Configure stats pid to 11003
2025-05-24 17:13:42,041 INFO    MainThread:11003 [wandb_setup.py:_flush():70] Loading settings from /home/vatsal/.config/wandb/settings
2025-05-24 17:13:42,041 INFO    MainThread:11003 [wandb_setup.py:_flush():70] Loading settings from /home/vatsal/NWM/fno_sevir/wandb/settings
2025-05-24 17:13:42,041 INFO    MainThread:11003 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-05-24 17:13:42,041 INFO    MainThread:11003 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /home/vatsal/NWM/fno_sevir/wandb/run-20250524_171342-7vuqx7lm/logs/debug.log
2025-05-24 17:13:42,041 INFO    MainThread:11003 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /home/vatsal/NWM/fno_sevir/wandb/run-20250524_171342-7vuqx7lm/logs/debug-internal.log
2025-05-24 17:13:42,042 INFO    MainThread:11003 [wandb_init.py:init():852] calling init triggers
2025-05-24 17:13:42,042 INFO    MainThread:11003 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-24 17:13:42,042 INFO    MainThread:11003 [wandb_init.py:init():893] starting backend
2025-05-24 17:13:42,042 INFO    MainThread:11003 [wandb_init.py:init():897] sending inform_init request
2025-05-24 17:13:42,050 INFO    MainThread:11003 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-24 17:13:42,050 INFO    MainThread:11003 [wandb_init.py:init():907] backend started and connected
2025-05-24 17:13:42,053 INFO    MainThread:11003 [wandb_init.py:init():1005] updated telemetry
2025-05-24 17:13:42,059 INFO    MainThread:11003 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-05-24 17:13:42,904 INFO    MainThread:11003 [wandb_init.py:init():1104] starting run threads in backend
2025-05-24 17:13:43,004 WARNING MainThread:11003 [wandb_init.py:init():1681] [no run ID] interrupted
Traceback (most recent call last):
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/wandb/sdk/wandb_init.py", line 1677, in init
    return wi.init(run_settings, run_config, run_printer)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/wandb/sdk/wandb_init.py", line 1149, in init
    run._on_start()
    ~~~~~~~~~~~~~^^
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 2602, in _on_start
    self._backend.interface.publish_python_packages(working_set())
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 345, in publish_python_packages
    for pkg in working_set:
               ^^^^^^^^^^^
  File "/home/vatsal/NWM/SSBware/senv/lib/python3.13/site-packages/wandb/util.py", line 1941, in working_set
    yield InstalledDistribution(key=d.metadata["Name"], version=d.version)
                                                                ^^^^^^^^^
  File "/home/vatsal/miniconda3/lib/python3.13/importlib/metadata/__init__.py", line 486, in version
    return self.metadata['Version']
           ^^^^^^^^^^^^^
  File "/home/vatsal/miniconda3/lib/python3.13/importlib/metadata/__init__.py", line 471, in metadata
    return _adapters.Message(email.message_from_string(text))
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/vatsal/miniconda3/lib/python3.13/email/__init__.py", line 37, in message_from_string
    return Parser(*args, **kws).parsestr(s)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/vatsal/miniconda3/lib/python3.13/email/parser.py", line 64, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vatsal/miniconda3/lib/python3.13/email/parser.py", line 53, in parse
    feedparser.feed(data)
    ~~~~~~~~~~~~~~~^^^^^^
  File "/home/vatsal/miniconda3/lib/python3.13/email/feedparser.py", line 176, in feed
    self._call_parse()
    ~~~~~~~~~~~~~~~~^^
  File "/home/vatsal/miniconda3/lib/python3.13/email/feedparser.py", line 180, in _call_parse
    self._parse()
    ~~~~~~~~~~~^^
  File "/home/vatsal/miniconda3/lib/python3.13/email/feedparser.py", line 240, in _parsegen
    self._parse_headers(headers)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/vatsal/miniconda3/lib/python3.13/email/feedparser.py", line 489, in _parse_headers
    self._cur.set_raw(*self.policy.header_source_parse(lastvalue))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2025-05-24 17:13:43,916 INFO    MsgRouterThr:11003 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 0 handles.
